using LazurdIT.FluentOrm.Common;
using System;

namespace PetAdoption.Shared
{
    [FluentTable("AdoptionRequests")]
    public class AdoptionModel : IFluentModel
    {
        [FluentField(name: "Id", autoGenerated: true, isPrimary: true, allowNull: false)] // Match database column
        public int Id { get; set; }

        [FluentField(name: "PetId", allowNull: false)]
        public int PetId { get; set; }

        [FluentField(name: "RequesterName", allowNull: false)]
        public string RequesterName { get; set; } = string.Empty;

        [FluentField(name: "RequestDate", allowNull: false)]
        public DateTime RequestDate { get; set; } = DateTime.Now;

        [FluentField(name: "Status", allowNull: false)]
        public string Status { get; set; } = "Pending";

        public override string ToString()
        {
            return $"AdoptionRequest: Id: {Id}, PetId: {PetId}, Requester: {RequesterName}, Date: {RequestDate}, Status: {Status}";
        }
    }
}
