using LazurdIT.FluentOrm.Common;
using System;

namespace PetAdoption.Shared
{
    [FluentTable("Owners")]
    public class OwnerModel : IFluentModel
    {
        [FluentField(name: "Id", autoGenerated: true, isPrimary: true, allowNull: false)] // Match database column
        public int Id { get; set; }

        [FluentField(name: "PetId", allowNull: false)]
        public int PetId { get; set; }

        [FluentField(name: "OwnerName", allowNull: false)]
        public string OwnerName { get; set; } = string.Empty;

        [FluentField(name: "AdoptionDate", allowNull: false)]
        public DateTime AdoptionDate { get; set; } = DateTime.Now;

        public override string ToString()
        {
            return $"Owner: Id: {Id}, PetId: {PetId}, Owner: {OwnerName}, Adoption Date: {AdoptionDate}";
        }
    }
}
