using LazurdIT.FluentOrm.Common;
using System;

namespace PetAdoption.Shared
{
    [FluentTable("Pets")]
    public class PetModel : IFluentModel
    {
        [FluentField(name: "Id", autoGenerated: true, isPrimary: true, allowNull: false)]
        public int Id { get; set; }

        [FluentField(name: "Name", allowNull: false)]
        public string Name { get; set; } = string.Empty;

        [FluentField(name: "Age", allowNull: false)]
        public int Age { get; set; }

        [FluentField(name: "Breed", allowNull: true)]
        public string? Breed { get; set; }

        [FluentField(name: "AdoptionStatus", allowNull: false)]
        public string AdoptionStatus { get; set; } = "Available";

        public override string ToString()
        {
            return $"Pet: Id: {Id}, Name: {Name}, Age: {Age}, Breed: {Breed}, Status: {AdoptionStatus}";
        }
    }

}
